import { useState } from "react";
import { FaBriefcase, FaTrash } from "react-icons/fa6";
import { useTranslation } from "react-i18next";
import "../styles/pages/Income.css";
function Income({ rendas, carregarRendas, criarRenda, atualizarRenda, deletarRendaPorId }) {
  const { t, i18n } = useTranslation(); const [extraDescricao, setExtraDescricao] = useState(""); const [extraValor, setExtraValor] = useState("");
  const rendaBase = rendas.find((renda) => renda.tipo === "BASE");
  function salvarBase(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const dados = { descricao: form.get("descricao"), valor: Number(form.get("valor")), tipo: "BASE" }; const request = rendaBase ? atualizarRenda(rendaBase.id, dados) : criarRenda(dados); request.then(carregarRendas); }
  function adicionarExtra(event) { event.preventDefault(); criarRenda({ descricao: extraDescricao, valor: Number(extraValor), tipo: "EXTRA" }).then(() => { carregarRendas(); setExtraDescricao(""); setExtraValor(""); }); }
  const moeda = (valor) => new Intl.NumberFormat(i18n.language, { style: "currency", currency: "BRL" }).format(Number(valor));
  return <div className="income-page"><div className="page-header"><h1>{t("incomePage.title")}</h1><p>{t("incomePage.subtitle")}</p></div><section className="income-section"><div><h2>{t("incomePage.baseTitle")}</h2><p>{t("incomePage.baseDescription")}</p></div><form className="income-form" onSubmit={salvarBase}><input name="descricao" required placeholder={t("incomePage.basePlaceholder")} defaultValue={rendaBase?.descricao} /><input name="valor" required type="number" step="0.01" placeholder={t("incomePage.amount")} defaultValue={rendaBase?.valor} /><button type="submit">{t(rendaBase ? "incomePage.updateBase" : "incomePage.saveBase")}</button></form></section><section className="income-section"><div><h2>{t("incomePage.extraTitle")}</h2><p>{t("incomePage.extraDescription")}</p></div><form className="income-form" onSubmit={adicionarExtra}><input required placeholder={t("incomePage.extraPlaceholder")} value={extraDescricao} onChange={(event) => setExtraDescricao(event.target.value)} /><input required type="number" step="0.01" placeholder={t("incomePage.amount")} value={extraValor} onChange={(event) => setExtraValor(event.target.value)} /><button type="submit">{t("incomePage.addExtra")}</button></form></section><section className="income-list"><h2>{t("incomePage.registered")}</h2>{rendas.length === 0 ? <div className="income-empty"><FaBriefcase /><h3>{t("incomePage.empty")}</h3><p>{t("incomePage.emptyMessage")}</p></div> : rendas.map((renda) => <div className="income-item" key={renda.id}><div className="income-left"><div className="income-icon"><FaBriefcase /></div><div><h3>{renda.descricao}</h3><span>{renda.tipo === "BASE" ? t("incomePage.base") : t("incomePage.extra")}</span></div></div><div className="income-right"><strong>{moeda(renda.valor)}</strong><button type="button" aria-label={t("incomePage.delete")} onClick={() => deletarRendaPorId(renda.id).then(carregarRendas)}><FaTrash /></button></div></div>)}</section></div>;
}
export default Income;
