import { FaTrash, FaBurger, FaCar, FaGamepad, FaBook, FaBox } from "react-icons/fa6";
import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import "../styles/pages/Transactions.css";
const categoryIcons = { ALIMENTACAO: <FaBurger />, TRANSPORTE: <FaCar />, LAZER: <FaGamepad />, ESTUDOS: <FaBook />, OUTROS: <FaBox /> };
function Transactions({ descricao, setDescricao, valor, setValor, categoria, setCategoria, categoriasFormulario, transacoes, adicionarTransacoes, deletarTransacao }) {
  const { t, i18n } = useTranslation(); const [busca, setBusca] = useState(""); const [filtroCategoria, setFiltroCategoria] = useState("TODAS"); const [periodo, setPeriodo] = useState(() => new Date().toISOString().slice(0, 7));
  const transacoesFiltradas = useMemo(() => transacoes.filter((item) => item.tipo === "SAIDA").filter((item) => filtroCategoria === "TODAS" || item.categoria === filtroCategoria).filter((item) => !periodo || String(item.data).startsWith(periodo)).filter((item) => `${item.descricao} ${item.categoria}`.toLowerCase().includes(busca.toLowerCase())), [transacoes, filtroCategoria, periodo, busca]);
  return <div className="transactions-page"><div className="page-header"><h1>{t("transactions.title")}</h1><p>{t("transactions.subtitle")}</p></div><div className="transactions-form-card"><form className="transactions-form" onSubmit={adicionarTransacoes}><input required placeholder={t("transactions.description")} value={descricao} onChange={(e) => setDescricao(e.target.value)} /><input required type="number" step="0.01" placeholder={t("transactions.amount")} value={valor} onChange={(e) => setValor(e.target.value)} /><select value={categoria} onChange={(e) => setCategoria(e.target.value)}>{categoriasFormulario.map((cat) => <option key={cat.value} value={cat.value}>{cat.label}</option>)}</select><button className="add-btn" type="submit">{t("transactions.add")}</button></form></div><div className="transactions-toolbar"><input className="transactions-search" placeholder={t("transactions.search")} value={busca} onChange={(event) => setBusca(event.target.value)} /><select className="transactions-filter" value={filtroCategoria} onChange={(event) => setFiltroCategoria(event.target.value)}><option value="TODAS">{t("transactions.allCategories")}</option>{categoriasFormulario.map((cat) => <option key={cat.value} value={cat.value}>{cat.label}</option>)}</select><input className="transactions-period" type="month" value={periodo} onChange={(event) => setPeriodo(event.target.value)} aria-label={t("transactions.filterMonth")} /></div><div className="transactions-list">{transacoesFiltradas.length === 0 ? <div className="transactions-empty">{t("transactions.empty")}</div> : transacoesFiltradas.map((item) => <div className="transaction-card" key={item.id}><div className="transaction-left"><div className="transaction-icon expense">{categoryIcons[item.categoria]}</div><div className="transaction-info"><h3>{item.descricao}</h3><p>{new Date(`${item.data}T00:00:00`).toLocaleDateString(i18n.language)}</p><span>{categoryIcons[item.categoria]} {t(`categories.${item.categoria}`)}</span></div></div><div className="transaction-right"><strong className="transaction-value">- {new Intl.NumberFormat(i18n.language, { style: "currency", currency: "BRL" }).format(Number(item.valor))}</strong><button type="button" aria-label={t("transactions.delete")} onClick={() => deletarTransacao(item.id)}><FaTrash /></button></div></div>)}</div></div>;
}
export default Transactions;
