import { useEffect, useMemo, useState } from "react";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid, Legend } from "recharts";
import { useTranslation } from "react-i18next";
import { buscarGastosMensais } from "../../services/api";
import "../../styles/components/FinancialChart.css";
const series = [{ key: "Food", fallback: "food", translation: "charts.food", color: "#3B82F6" }, { key: "Transport", fallback: "transport", translation: "charts.transport", color: "#10B981" }, { key: "Leisure", fallback: "leisure", translation: "charts.leisure", color: "#F59E0B" }, { key: "Education", fallback: "education", translation: "charts.education", color: "#EC4899" }, { key: "Others", fallback: "others", translation: "charts.others", color: "#8B5CF6" }];
function monthDate(item) { const raw = item.month ?? item.mes ?? item.date ?? item.periodo; if (typeof raw === "number") return new Date(2000, raw - 1, 1); if (/^\d{4}-\d{2}/.test(raw || "")) return new Date(`${raw.slice(0, 7)}-01T00:00:00`); const parsed = new Date(raw); return Number.isNaN(parsed.getTime()) ? null : parsed; }
function FinancialChart() { const { t, i18n } = useTranslation(); const [dados, setDados] = useState([]); useEffect(() => { buscarGastosMensais().then((response) => setDados(response || [])).catch(() => setDados([])); }, []); const chartData = useMemo(() => dados.map((item) => ({ ...item, monthLabel: monthDate(item)?.toLocaleDateString(i18n.language, { month: "long" }) || String(item.month ?? item.mes ?? "") , order: monthDate(item)?.getTime() || Number.MAX_SAFE_INTEGER })).sort((a, b) => a.order - b.order), [dados, i18n.language]); return <section className="financial-chart"><div className="chart-header"><div><h2>{t("charts.monthlyExpenseAnalysis")}</h2><span>{t("charts.spendingYear")}</span></div></div><div className="chart-content"><ResponsiveContainer width="100%" height={260}><LineChart data={chartData}><CartesianGrid stroke="#243041" strokeDasharray="4 4" /><XAxis dataKey="monthLabel" stroke="#8EA2C0" /><YAxis stroke="#8EA2C0" /><Tooltip contentStyle={{ backgroundColor: "#1E293B", borderColor: "#334155", color: "#FFF" }} /><Legend />{series.map((item) => <Line key={item.key} type="monotone" dataKey={chartData[0]?.[item.key] !== undefined ? item.key : item.fallback} name={t(item.translation)} stroke={item.color} strokeWidth={3} dot={{ fill: item.color, r: 4 }} />)}</LineChart></ResponsiveContainer></div></section>; }
export default FinancialChart;
